// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getUserByEmail.sql

package database

import (
	"context"
)

const getUsetByEmail = `-- name: GetUsetByEmail :one
SELECT id, created_at, updated_at, email, hashed_password FROM users
WHERE email = $1
`

func (q *Queries) GetUsetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUsetByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
